export const styles = {
  container: {
    padding: '1.5rem',
    backgroundColor: 'var(--sapBackgroundColor, #f7f7f7)',
    minHeight: '100vh',
    fontFamily: '"72", Arial, sans-serif',
  },
  header: {
    marginBottom: '1.25rem',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px solid var(--sapGroup_ContentBorderColor, #e0e0e0)',
    paddingBottom: '1rem',
  },
  title: {
    fontSize: '1.5rem',
    fontWeight: '500',
    color: 'var(--sapTextColor, #32363a)',
    textTransform: 'capitalize',
  },
  button: {
    backgroundColor: 'var(--sapButton_Background, #0a6ed1)',
    color: 'var(--sapButton_TextColor, #fff)',
    fontWeight: '500',
    padding: '0.5rem 1rem',
    borderRadius: '0.25rem',
    border: 'none',
    cursor: 'pointer',
    transition: 'background-color 0.3s ease',
  },
  buttonHover: {
    backgroundColor: 'var(--sapButton_Hover_Background, #0854a0)',
  },
  loadingContainer: {
    textAlign: 'center',
    padding: '2rem',
    color: 'var(--sapContent_LabelColor, #6a6a6a)',
    fontSize: '1.2rem',
  },
  card: {
    marginTop: '1rem',
    backgroundColor: 'var(--sapTile_Background, #ffffff)',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.07)',
    borderRadius: '0.5rem',
    border: 'none',
    overflow: 'hidden',
  },
  table: {
    width: '100%',
    borderCollapse: 'separate',
    borderSpacing: 0,
    fontSize: '0.875rem',
    '--_ui5_tc_header_row_outline_width': '0',
    '--_ui5_tc_row_outline_width': '0',
    tableLayout: 'fixed',
    '--_ui5_tc_cell_padding': '0.25rem 0.5rem',
    '--sapUiContentDisabledTextColor': 'var(--sapTextColor, #32363a)',
    '--sapContent_GridSize': '0.25rem',
    '--sapUiTableRowHeight': 'auto',
    '--sapUiTableRowHdrHeight': '3rem',
    '--_ui5_tc_cell_vertical_align': 'top',
    '--sapList_HeaderBorderColor': 'var(--sapGroup_ContentBorderColor, #e0e0e0)',
    '--sapList_BorderColor': 'var(--sapGroup_ContentBorderColor, #e8e8e8)',
    '--_ui5_tc_row_hover_outline_color': 'transparent',
    '--_ui5_analytical_table_header_cell_vertical_align': 'bottom',
    '--sapUiListHeaderBorderWidth': '0',
    '--sapUiFieldBorderWidth': '0',
    '--sapUiListTableFixedColumnWidth': 'auto',
    '--sapUiBaseBG': 'var(--sapTile_Background, #ffffff)',
    '--sapUiListHeaderBackground': 'var(--sapList_HeaderBackground, #fafafa)',
    '--sapUiListSelectionBackgroundColor': 'var(--sapList_SelectionBackgroundColor, #f0f7fd)',
    '--_ui5_tc_row_outline_color': 'transparent',
    '--_ui5_tc_cell_outline_width': '0',
    '--_ui5_tc_row_outline_width': '0',
    '--_ui5_tc_header_cell_default_border_color': 'var(--sapGroup_ContentBorderColor, #e5e5e5)',
    '--_ui5_tc_headerBorderWidth': '0 0 1px 0',
    '--_ui5_analytical_table_header_box_shadow': 'none',
    '--sapGroup_TitleBackground': 'var(--sapGroup_TitleBackground, #f5f5f5)',
    '--_ui5_analytical_table_header_background_color': 'var(--sapGroup_TitleBackground, #f5f5f5)',
    
    // Ajustes para que la tabla sea más compacta
    '--_ui5_tc_row_height': 'auto',
    '--_ui5_tc_header_row_height': '2.5rem',
    '--_ui5_tc_row_highlight_display': 'none',
    '--sapUiElementLineHeight': '1.3',
    '--sapUiListTableHeaderFontSize': '0.75rem',
    '--sapUiTextDisabled': 'var(--sapContent_LabelColor, #666)',
    '--_ui5_tc_padding': '0',
    '--_ui5_tc_header_cell_padding': '0.5rem 0.75rem',
  },
  tableHeader: {
    fontWeight: '600',
    textAlign: 'left',
    color: 'var(--sapContent_LabelColor, #32363a)',
    backgroundColor: 'var(--sapList_HeaderBackground, #f7f7f7)',
    borderBottom: '1px solid var(--sapGroup_ContentBorderColor, #e5e5e5)',
    padding: '0.5rem 0.5rem',
    fontSize: '0.75rem',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  tableRow: {
    transition: 'background-color 0.2s ease',
    borderBottom: '1px solid var(--sapGroup_ContentBorderColor, #e5e5e5)',
    height: 'auto',
    minHeight: '4rem',
  },
  tableCell: {
    padding: '0.5rem 0.5rem',
    textAlign: 'left',
    verticalAlign: 'middle',
    color: 'var(--sapTextColor, #32363a)',
    lineHeight: '1.4',
  },
  dialogFooter: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '1rem',
    paddingTop: '1rem',
    borderTop: '1px solid var(--sapGroup_ContentBorderColor, #e0e0e0)',
  },
  input: {
    width: '100%',
    padding: '0.5rem',
    border: '1px solid var(--sapField_BorderColor, #d9d9d9)',
    borderRadius: '0.25rem',
    fontSize: '0.875rem',
    marginBottom: '1rem',
    transition: 'border-color 0.3s ease',
  },
  inputFocus: {
    borderColor: 'var(--sapField_Hover_BorderColor, #0a6ed1)',
    outline: 'none',
    boxShadow: '0 0 0 2px rgba(10, 110, 209, 0.2)',
  },
  formLabel: {
    fontWeight: '500',
    marginBottom: '0.5rem',
    display: 'block',
    color: 'var(--sapContent_LabelColor, #32363a)',
    fontSize: '0.875rem',
  },
  icon: {
    fontSize: '2rem',
    color: 'var(--sapContent_IconColor, #0a6ed1)',
    marginBottom: '1rem',
  },
  successStatus: {
    color: 'var(--sapPositiveColor, #107e3e)',
    fontWeight: '600',
  },
  warningStatus: {
    color: 'var(--sapCriticalColor, #e9730c)',
    fontWeight: '600',
  },
  errorStatus: {
    color: 'var(--sapNegativeColor, #bb0000)',
    fontWeight: '600',
  },
  dialogTitle: {
    fontSize: '1.25rem',
    fontWeight: '500',
    color: 'var(--sapTitleColor, #32363a)',
    marginBottom: '1rem',
  },
  link: {
    color: 'var(--sapLinkColor, #0a6ed1)',
    textDecoration: 'none',
    borderBottom: '1px solid transparent',
    transition: 'border-color 0.2s ease',
    cursor: 'pointer',
  },
  dialog: {
    maxWidth: '600px',
    margin: 'auto',
    padding: '1.5rem',
    backgroundColor: 'var(--sapTile_Background, #ffffff)',
    borderRadius: '0.5rem',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
    position: 'relative',
    zIndex: 1000,
    '& .ui5-popup-root': {
      backgroundColor: 'transparent !important',
    }
  },
  dialogOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 999,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backdropFilter: 'blur(2px)',
  },
  detailSection: {
    marginBottom: '1rem',
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0.25rem 0.5rem',
    borderRadius: '1rem',
    fontWeight: '600',
    fontSize: '0.75rem',
  },
  badgeSuccess: {
    backgroundColor: 'rgba(16, 126, 62, 0.1)',
    color: 'var(--sapPositiveColor, #107e3e)',
  },
  badgeWarning: {
    backgroundColor: 'rgba(233, 115, 12, 0.1)',
    color: 'var(--sapCriticalColor, #e9730c)',
  },
  badgeInfo: {
    backgroundColor: 'rgba(10, 110, 209, 0.1)',
    color: 'var(--sapInformativeColor, #0a6ed1)',
  },
  filterBar: {
    marginBottom: '0',
    padding: '0.5rem 1rem',
    backgroundColor: 'var(--sapList_HeaderBackground, #fdfdfd)',
    borderBottom: '1px solid var(--sapGroup_ContentBorderColor, #e5e5e5)',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.5rem',
  },
  tableContainer: {
    borderRadius: '0.25rem',
    overflow: 'hidden',
    border: '1px solid var(--sapGroup_ContentBorderColor, #e5e5e5)',
    tableLayout: 'fixed',
    width: '100%',
  },
  tablePagination: {
    display: 'flex',
    justifyContent: 'flex-end',
    padding: '0.5rem 1rem',
    backgroundColor: 'var(--sapList_FooterBackground, #fafafa)',
    borderTop: '1px solid var(--sapGroup_ContentBorderColor, #e5e5e5)',
  },
  cellText: {
    fontSize: '0.75rem',
    color: 'var(--sapTextColor, #32363a)',
    wordBreak: 'break-word',
    lineHeight: '1.3',
    display: 'block',
    width: '100%',
  },
  cellHeading: {
    fontSize: '0.875rem',
    fontWeight: '600',
    color: 'var(--sapTextColor, #32363a)',
    marginBottom: '0.25rem',
    wordBreak: 'break-word',
    lineHeight: '1.3',
    display: 'block',
  },
  cellIcon: {
    fontSize: '0.75rem',
    marginRight: '0.25rem',
    flexShrink: 0,
    color: 'var(--sapContent_IconColor, #0854a0)',
  },
  headerBar: {
    padding: '0.5rem 1rem',
    borderBottom: '1px solid var(--sapGroup_ContentBorderColor, #e5e5e5)',
    backgroundColor: 'var(--sapList_HeaderBackground, #fdfdfd)',
    height: 'auto',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  summaryCard: {
    padding: '1.5rem',
    borderRadius: '0.5rem',
    backgroundColor: 'var(--sapTile_Background, #ffffff)',
    border: '1px solid var(--sapGroup_ContentBorderColor, #e0e0e0)',
    boxShadow: '0 2px 6px rgba(0,0,0,0.1)',
    flex: '1 1 20rem',
  },
  flexCardContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '1.5rem',
  },
  tabBar: {
    marginBottom: '1.5rem',
    borderBottom: '1px solid var(--sapGroup_ContentBorderColor, #e0e0e0)',
    background: 'transparent',
  },
  tabIcon: {
    marginRight: '0.5rem', 
    fontSize: '1rem'
  },
  valueText: {
    fontWeight: '600', 
    fontSize: '1.25rem', 
    color: 'var(--sapIndicator, #0854a0)'
  },
  labelText: {
    fontSize: '0.75rem', 
    color: 'var(--sapContent_LabelColor, #6a6d70)'
  },
  cardTitle: {
    fontWeight: '600', 
    fontSize: '1.125rem', 
    marginBottom: '0.75rem'
  },
  cardDescription: {
    fontSize: '0.875rem', 
    color: 'var(--sapContent_LabelColor, #6a6d70)', 
    marginBottom: '1rem'
  },
  dialogStyles: {
    '& .ui5-popup-root': {
      backgroundColor: 'transparent !important',
    },
    '& .ui5-dialog-header': {
      backgroundColor: 'var(--sapBackgroundColor) !important',
    },
    '& .ui5-dialog-content': {
      backgroundColor: 'var(--sapBackgroundColor) !important',
    },
    '& .ui5-dialog-footer': {
      backgroundColor: 'var(--sapBackgroundColor) !important',
    }
  },
};
