name: CI Monorepo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Front2
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: { node-version: '18.x' }

      - name: Install deps
        run: npm install

      - name: Run tests
        run: npm test

      - name: Lint & Build
        run: |
          npm run lint
          npm run build

  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Back
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: { node-version: '18.x' }

      - name: Install deps
        run: npm install

      - name: Run tests
        run: npm test

      - name: Lint & Build
        run: |
          npm run lint
          npm run build
