name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Lint code
        run: npm run lint

      # Este paso levanta tu app (por ejemplo para validar que arranca),
      # pero aunque falle, la job NO fallará gracias a continue-on-error.
      - name: Start app for smoke test
        run: npm start &
        continue-on-error: true

      # Paso "deploy" simulado: no hace push a Vercel/Railway,
      # solo emite un status check.
      - name: Deploy (placeholder)
        run: echo "✅ Deploy placeholder – CI está listo para Vercel/Railway"
        continue-on-error: true
